name: Ping API daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # 08:00 UTC = 09:00 London (UK time, BST)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Truthy News API
        run: curl -I https://truthy-news.onrender.com/api/articles
