name: Ping API daily

on:
  schedule:
    - cron: '10 15 * * *'  # 15:10 UTC = 16:10 London (BST)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Truthy News API
        run: curl -I https://truthy-news.onrender.com/api/articles